# 로컬 윈도우즈에서 DB-Boot-React 실행하기
services:
  mysql-svc:
    image: mariadb:10.11.14
    ports:
    - "3306:3306"
    volumes:
      #- C:/docker-volume/mariadb/conf.d:/etc/mysql/conf.d
      - C:/mydeploy/docker-volume/mariadb/store:/var/lib/mysql
    env_file: C:/mydeploy/docker-volume/mariadb/env/.env

  backend:
    image: hands7/miniproject3-backend:0.1
    ports:
      - "8080:8080"
    depends_on:
      - mysql-svc
      - ai
    restart: always
    env_file: C:/mydeploy/docker-volume/mariadb/env/.env
    # environment:
      # DB_HOST: 'mysql-svc'
      # DB_PORT: '3306'
      # DB_DATABASE: 'boot_db'
      # DB_USERNAME: 'boot'
      # DB_PASSWORD: 'boot'
    environment:
      - PYTHON_SERVER_URL=http://ai:8000

  frontend:
    image: hands7/miniproject3_frontend:0.3
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_APIURL=http://backend:8080/api
      - VITE_MODE=Prod
    restart: always

  ai:
    image: hands7/miniproject3-ai:0.1
    ports:
      - "8000:8000"
    depends_on:
      - mysql-svc
    restart: always

    env_file:
      - ../AI/.env

    volumes:
      - ../AI/uploaded_pdfs:/app/uploaded_pdfs
      - ../AI/vector_stores:/app/vector_stores

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s