version: '3.9'

services:

  # 백엔드 (Spring Boot + MariaDB 연동)
  backend:
    image: hands7/miniproject3-backend:0.1
    container_name: backend
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=maria
      - SPRING_DATASOURCE_PASSWORD=boot
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./backend/uploads:/app/uploads            
    restart: unless-stopped


  # 데이터베이스(MariaDB)
  mariadb:
    image: mariadb:10.11.8
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=study_db
      - MYSQL_USER=boot
      - MYSQL_PASSWORD=boot
    ports:
      - "3306:3306"
    volumes:
      - C:\mydeploy\docker-volume\mariadb\store:/var/lib/mysql              
    restart: unless-stopped

# 볼륨 정의
volumes:
  mariadb_data:



  backend:
    image: hands7/miniproject3-backend:0.1
    ports:
      - "8080:8080"
    depends_on:
      - mysql-svc
    restart: always
    env_file: C:/mydeploy/docker-volume/mariadb/env/.env
    # environment:
      # DB_HOST: 'mysql-svc'
      # DB_PORT: '3306'
      # DB_DATABASE: 'boot_db'
      # DB_USERNAME: 'boot'
      # DB_PASSWORD: 'boot'